// scripts/migrateActivitiesFromJson.ts
import 'dotenv/config';
import mongoose from 'mongoose';
import { readFileSync } from 'fs';
import { resolve } from 'path';
import { Activity } from '../src/models/activity.model';

/**
 * Migration Script: Activities from JSON to MongoDB
 *
 * Purpose: Import activity data from static JSON files into MongoDB
 * Source Files:
 *   - data/content/en/activities.json
 *   - data/content/fr/activities.json
 */

interface JsonActivity {
  id: string;
  name: string;
  description: string;
  coverImage: string;
  images: string[];
  duration: string;
  location: string;
  groupSize: string;
  price: number;
  metadata: {
    title: string;
    description: string;
    path: string;
    image: string;
    alt: string;
  };
}

/**
 * Transform JSON activity data to MongoDB schema format
 */
function transformActivityData(
  jsonActivity: JsonActivity,
  locale: 'en' | 'fr'
) {
  // Extract localeGroupId from JSON id field (e.g., "activity-2" → "activity-2")
  const localeGroupId = jsonActivity.id;

  return {
    name: jsonActivity.name,
    description: jsonActivity.description,
    coverImage: jsonActivity.coverImage,
    images: jsonActivity.images || [],
    duration: jsonActivity.duration,
    location: jsonActivity.location,
    groupSize: jsonActivity.groupSize,
    price: jsonActivity.price || 0,
    metadata: {
      title: jsonActivity.metadata.title,
      description: jsonActivity.metadata.description,
      path: jsonActivity.metadata.path,
      image: jsonActivity.metadata.image,
      alt: jsonActivity.metadata.alt,
    },
    localeGroupId, // Link EN/FR translations with the same ID
    locale,
    status: 'active' as const,
    availabilityStatus: 'available' as const,
    tags: [], // Will be auto-generated by pre-save hook
    packIds: [],
  };
}

/**
 * Main migration function
 */
async function migrateActivities() {
  try {
    // 1. Connect to MongoDB
    console.log('🔌 Connecting to MongoDB...');
    const MONGODB_URI =
      process.env.MONGODB_URI || 'mongodb://localhost:27017/explorekg';
    await mongoose.connect(MONGODB_URI);
    console.log('✅ Connected to MongoDB\n');

    // 2. Clear existing activities
    console.log('🗑️  Clearing existing activities...');
    const deleteResult = await Activity.deleteMany({});
    console.log(
      `   Deleted ${deleteResult.deletedCount} existing activities\n`
    );

    // 3. Read JSON files
    console.log('📖 Reading JSON files...');

    const enPath = resolve(__dirname, '../data/content/en/activities.json');
    const frPath = resolve(__dirname, '../data/content/fr/activities.json');

    const enActivities: JsonActivity[] = JSON.parse(
      readFileSync(enPath, 'utf-8')
    );
    const frActivities: JsonActivity[] = JSON.parse(
      readFileSync(frPath, 'utf-8')
    );

    console.log(`   English activities: ${enActivities.length}`);
    console.log(`   French activities: ${frActivities.length}\n`);

    // 4. Transform and insert English activities
    console.log('🌍 Migrating English activities...');
    const enTransformed = enActivities.map(activity =>
      transformActivityData(activity, 'en')
    );
    const enInserted = await Activity.insertMany(enTransformed);
    console.log(`   ✅ Inserted ${enInserted.length} English activities\n`);

    // 5. Transform and insert French activities
    console.log('🇫🇷 Migrating French activities...');
    const frTransformed = frActivities.map(activity =>
      transformActivityData(activity, 'fr')
    );
    const frInserted = await Activity.insertMany(frTransformed);
    console.log(`   ✅ Inserted ${frInserted.length} French activities\n`);

    // 6. Display statistics
    console.log('📊 Migration Statistics:');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━');
    console.log(
      `   Total activities migrated: ${enInserted.length + frInserted.length}`
    );
    console.log(`   English (en):             ${enInserted.length}`);
    console.log(`   French (fr):              ${frInserted.length}`);
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');

    // 7. Sample activity
    const sampleActivity = await Activity.findOne({ locale: 'en' });
    if (sampleActivity) {
      console.log('📝 Sample Activity (English):');
      console.log(`   Name:        ${sampleActivity.name}`);
      console.log(`   Location:    ${sampleActivity.location}`);
      console.log(`   Duration:    ${sampleActivity.duration}`);
      console.log(
        `   Price:       $${sampleActivity.price} ${sampleActivity.price === 0 ? '(FREE)' : ''}`
      );
      console.log(`   Group Size:  ${sampleActivity.groupSize}`);
      console.log(`   Tags:        ${sampleActivity.tags.join(', ')}`);
      console.log(`   Path:        ${sampleActivity.metadata.path}\n`);
    }

    // 8. Verify indexes
    console.log('🔍 Verifying indexes...');
    const indexes = await Activity.collection.getIndexes();
    console.log(`   Total indexes: ${Object.keys(indexes).length}`);
    Object.keys(indexes).forEach(indexName => {
      console.log(`   - ${indexName}`);
    });
    console.log();

    // 9. Success message
    console.log('✅ Activities migration completed successfully!');
    console.log('━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n');
  } catch (error) {
    console.error('❌ Migration failed:', error);
    throw error;
  } finally {
    // Close database connection
    await mongoose.connection.close();
    console.log('🔌 Database connection closed\n');
  }
}

// Run migration
migrateActivities()
  .then(() => {
    console.log('🎉 Migration script completed');
    process.exit(0);
  })
  .catch(error => {
    console.error('💥 Migration script failed:', error);
    process.exit(1);
  });

// ✅ Migration script completed — Activities successfully imported from JSON.
