// scripts/migrateCarsFromJson.ts
import mongoose from 'mongoose';
import * as fs from 'fs';
import * as path from 'path';
import { Car } from '../src/models/car.model';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

/**
 * Migration Script: Cars from JSON to MongoDB
 * Reads cars.json files (en/fr) and imports them into MongoDB
 */

interface JSONCar {
  id: string;
  name: string;
  description: string;
  coverImage: string;
  price: number;
  currency: string;
  unit: string;
  seats: string;
  transmission: string;
  drive: string;
  luggage: string;
  fuel: string;
  metadata: {
    title: string;
    description: string;
    path: string;
    image: string;
    alt: string;
  };
  images: string[];
}

/**
 * Transform JSON car data to MongoDB car schema
 */
function transformCarData(jsonCar: JSONCar, locale: 'en' | 'fr') {
  // Extract localeGroupId from JSON id field (e.g., "car-1" → "car-1")
  const localeGroupId = jsonCar.id;

  return {
    name: jsonCar.name,
    description: jsonCar.description,
    coverImage: jsonCar.coverImage,
    pricing: {
      amount: jsonCar.price,
      currency: jsonCar.currency,
      unit: jsonCar.unit,
    },
    specs: {
      seats: jsonCar.seats,
      transmission: jsonCar.transmission,
      drive: jsonCar.drive,
      luggage: jsonCar.luggage,
      fuel: jsonCar.fuel,
    },
    metadata: {
      title: jsonCar.metadata.title,
      description: jsonCar.metadata.description,
      path: jsonCar.metadata.path,
      image: jsonCar.metadata.image,
      alt: jsonCar.metadata.alt,
    },
    images: jsonCar.images || [],
    tags: [], // Will be auto-generated by pre-save hook
    localeGroupId, // Link EN/FR translations with the same ID
    locale,
    status: 'active',
    availabilityStatus: 'available',
    packIds: [],
  };
}

/**
 * Main migration function
 */
async function migrateCars() {
  try {
    // Connect to MongoDB
    const mongoURI =
      process.env.MONGODB_URI || 'mongodb://localhost:27017/explorekg-dev';
    console.log('🔄 Connecting to MongoDB...');
    await mongoose.connect(mongoURI);
    console.log('✅ Connected to MongoDB');

    // Clear existing cars collection
    console.log('🗑️  Clearing existing cars...');
    await Car.deleteMany({});
    console.log('✅ Existing cars cleared');

    // Read English cars
    const enCarsPath = path.join(__dirname, '../data/content/en/cars.json');
    const enCarsData: JSONCar[] = JSON.parse(
      fs.readFileSync(enCarsPath, 'utf-8')
    );
    console.log(`📖 Found ${enCarsData.length} English cars`);

    // Read French cars
    const frCarsPath = path.join(__dirname, '../data/content/fr/cars.json');
    const frCarsData: JSONCar[] = JSON.parse(
      fs.readFileSync(frCarsPath, 'utf-8')
    );
    console.log(`📖 Found ${frCarsData.length} French cars`);

    // Transform and insert English cars
    console.log('🔄 Inserting English cars...');
    const enCars = enCarsData.map(car => transformCarData(car, 'en'));
    await Car.insertMany(enCars);
    console.log(`✅ Inserted ${enCars.length} English cars`);

    // Transform and insert French cars
    console.log('🔄 Inserting French cars...');
    const frCars = frCarsData.map(car => transformCarData(car, 'fr'));
    await Car.insertMany(frCars);
    console.log(`✅ Inserted ${frCars.length} French cars`);

    // Get final statistics
    const totalCars = await Car.countDocuments();
    const activeCars = await Car.countDocuments({ status: 'active' });
    const availableCars = await Car.countDocuments({
      availabilityStatus: 'available',
    });

    console.log('\n📊 Migration Summary:');
    console.log(`   Total cars: ${totalCars}`);
    console.log(`   Active cars: ${activeCars}`);
    console.log(`   Available for booking: ${availableCars}`);
    console.log(`   English versions: ${enCars.length}`);
    console.log(`   French versions: ${frCars.length}`);

    console.log('\n✅ Migration completed successfully!');
  } catch (error) {
    console.error('❌ Migration failed:', error);
    process.exit(1);
  } finally {
    // Close MongoDB connection
    await mongoose.connection.close();
    console.log('👋 MongoDB connection closed');
  }
}

// Run migration
if (require.main === module) {
  migrateCars()
    .then(() => {
      console.log('\n🎉 All done!');
      process.exit(0);
    })
    .catch(error => {
      console.error('\n💥 Fatal error:', error);
      process.exit(1);
    });
}

export { migrateCars };
